In [3]:
#Question1
import numpy as np
x=np.random.rand(10,1)
print("Formed Matrix Is \n",x)
print("Mean of the Above Matrix Is =",np.mean(x))

Formed Matrix Is 
 [[0.84812279]
 [0.37631806]
 [0.88289146]
 [0.9829351 ]
 [0.8006643 ]
 [0.65726642]
 [0.44574235]
 [0.19996483]
 [0.11375105]
 [0.85194948]]
Mean of the Above Matrix Is = 0.615960583499035


In [4]:
#Question2
x=np.random.rand(20,1)
print("Formed Matrix Is \n",x)
print("Variance of the formed matrix is =",np.var(x))
print("Standard deviation of the formed matrix is =",np.std(x))

Formed Matrix Is 
 [[0.73588639]
 [0.79345031]
 [0.51410577]
 [0.22763507]
 [0.46898359]
 [0.03041657]
 [0.51547947]
 [0.35842967]
 [0.33584869]
 [0.47450503]
 [0.80520987]
 [0.88715775]
 [0.8893693 ]
 [0.94004766]
 [0.55495372]
 [0.24779122]
 [0.14770488]
 [0.69494657]
 [0.84535402]
 [0.8229164 ]]
Variance of the formed matrix is = 0.07214197792472546
Standard deviation of the formed matrix is = 0.26859258724828106


In [5]:
#Question 3

A=np.random.rand(10,20)
B=np.random.rand(20,25)

x=np.matmul(A,B)
print("Matrix Formed After Multiplication\n",x)

print("Sum Of Newly Formed Matrix = ",np.sum(x))

Matrix Formed After Multiplication
 [[3.62359827 4.24301638 3.82162567 3.99636263 3.44428227 5.12149323
  3.20669504 3.85897472 4.31402405 4.38317332 5.29669574 5.46775999
  3.86333007 4.00483663 3.58785473 4.80467308 4.40255659 4.30468864
  4.58171917 4.65713371 5.37184221 3.75917151 4.88079698 4.36286931
  5.08756731]
 [3.14558798 4.34415802 3.5385499  3.29415475 3.41138726 3.27639781
  3.23852975 3.33984703 2.84526784 3.17526807 4.20650422 3.43043306
  3.14242263 2.74172969 3.21730167 3.37379824 3.2413316  3.37128846
  2.8477792  3.95207729 4.08425954 3.22082358 4.73739263 3.51449619
  3.39268731]
 [4.38030549 5.44988447 5.3618914  5.75262531 4.94619519 6.11031034
  4.00725404 4.1978474  5.13378433 4.47582128 5.5352081  5.41951139
  4.4530996  5.11322706 4.79845134 5.22135259 5.61902261 5.50411999
  5.38934465 5.09526438 4.54466172 4.84013302 6.10893044 4.78445735
  6.08303912]
 [4.77123145 6.14570184 4.92768558 4.77582091 5.04720349 5.4847489
  4.57441648 3.83532143 5.18621371 5.36

In [6]:
#Question 4
#f(x)=1 / (1 + exp(-x)) 
from math import exp
y=np.random.rand(10,1)
print(y)
l=[]
for i in y:
    l.append(1/(1+exp(-(i))))
    
print("\n\n\nAfter performing given function")
print(np.array(l).reshape(10,1))

[[0.64562473]
 [0.87433434]
 [0.92003171]
 [0.24063111]
 [0.49846165]
 [0.92103089]
 [0.84837162]
 [0.04660971]
 [0.76646406]
 [0.88919449]]



After performing given function
[[0.65602383]
 [0.70564678]
 [0.71504857]
 [0.55986917]
 [0.62209774]
 [0.71525211]
 [0.70022544]
 [0.51165032]
 [0.6827555 ]
 [0.70872392]]
